/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;

import CapaDatos.ClsConexion;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fundamentos DS
 */
public class WinInicio extends javax.swing.JFrame {

    /**
     * Creates new form WinInicio
     */
    ClsConexion base, agenda;
    String BasedeDatos;
    String nom, ape, telf;
    int clvA;
    float pP;
    public WinInicio() {
        initComponents();
         ArchBd.setVisible(false);
         PnlAgenda.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlAgenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        TxtTelefono = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtApellido = new javax.swing.JTextField();
        BtnAnt = new javax.swing.JButton();
        BtnSig = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        BtnGrabar = new javax.swing.JButton();
        BtnActuaProducto = new javax.swing.JButton();
        ArchBd = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnuAbrir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MnuCon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlAgenda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Teléfono:");
        PnlAgenda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        PnlAgenda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 55, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");
        PnlAgenda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        BtnAgregar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        PnlAgenda.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        TxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoActionPerformed(evt);
            }
        });
        PnlAgenda.add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 120, -1));

        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        PnlAgenda.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, -1));

        TxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApellidoActionPerformed(evt);
            }
        });
        PnlAgenda.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, -1));

        BtnAnt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnAnt.setText("Anterior");
        BtnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAntActionPerformed(evt);
            }
        });
        PnlAgenda.add(BtnAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        BtnSig.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnSig.setText("Siguiente");
        BtnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSigActionPerformed(evt);
            }
        });
        PnlAgenda.add(BtnSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        BtnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        PnlAgenda.add(BtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        BtnBorrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnBorrar.setText("Borrar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });
        PnlAgenda.add(BtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 80, -1));

        BtnGrabar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnGrabar.setText("Modificar");
        BtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarActionPerformed(evt);
            }
        });
        PnlAgenda.add(BtnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        BtnActuaProducto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnActuaProducto.setText("Actualizar");
        BtnActuaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActuaProductoActionPerformed(evt);
            }
        });
        PnlAgenda.add(BtnActuaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 100, -1));

        ArchBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchBdActionPerformed(evt);
            }
        });

        jMenu1.setText("Base de Datos");

        MnuAbrir.setText("Abrir");
        MnuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(MnuAbrir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Agenda");

        MnuCon.setText("Consultar");
        MnuCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuConActionPerformed(evt);
            }
        });
        jMenu2.add(MnuCon);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(PnlAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 83, Short.MAX_VALUE)
                    .addComponent(ArchBd, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 83, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(PnlAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addComponent(ArchBd, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 61, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAbrirActionPerformed
         ArchBd.setVisible(true);
    }//GEN-LAST:event_MnuAbrirActionPerformed

    private void ArchBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchBdActionPerformed
         File f=ArchBd.getSelectedFile();
        BasedeDatos=f.getAbsolutePath();
        ArchBd.setVisible(false);
        base=new ClsConexion(BasedeDatos);
    }//GEN-LAST:event_ArchBdActionPerformed

    private void TxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void TxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApellidoActionPerformed

    private void MnuConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuConActionPerformed
        PnlAgenda.setVisible(true);
        BtnAgregar.setVisible(false);
        try {
            // TODO add your handling code here:
            base.consulta("Agenda");
        } catch (SQLException ex) {
            Logger.getLogger(WinInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MnuConActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
         nom=TxtNombre.getText();
        ape=TxtApellido.getText();
        telf=TxtTelefono.getText();

        try {
            base.insertar("Agenda", nom, ape, telf);

           
            BtnSig.setVisible(true);
        BtnAnt.setVisible(true);
        BtnAgregar.setVisible(false);
        
        } catch (SQLException ex) {
            Logger.getLogger(WinInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    
       
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAntActionPerformed
                 try {
            // TODO add your handling code here:
            base.anterior();
            TxtNombre.setText(base.registros().getString("Nombre"));
            TxtApellido.setText(base.registros().getString("Apellido"));
            TxtTelefono.setText(base.registros().getString("Telefono"));
            clvA = base.registros().getInt("IdAgenda");  
        } catch (SQLException ex) {
            Logger.getLogger(WinInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
    
    }//GEN-LAST:event_BtnAntActionPerformed

    private void BtnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSigActionPerformed
         try {
            // TODO add your handling code here:
            base.siguiente();
            TxtNombre.setText(base.registros().getString("Nombre"));
            TxtApellido.setText(base.registros().getString("Apellido"));
            TxtTelefono.setText(base.registros().getString("Telefono"));
            clvA = base.registros().getInt("IdAgenda");  
        } catch (SQLException ex) {
            Logger.getLogger(WinInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSigActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        BtnAgregar.setVisible(true);
        BtnSig.setVisible(false);
        BtnAnt.setVisible(false);
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        try {
            base.eliminar("Agenda", clvA);

        } catch (SQLException ex) {
            Logger.getLogger(WinInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void BtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarActionPerformed
        nom=TxtNombre.getText();
        ape=TxtApellido.getText();
        telf=TxtTelefono.getText();

        try {
            base.actualizar("Agenda", nom, ape, telf, clvA);
            BtnGrabar.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(WinInicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BtnGrabarActionPerformed

    private void BtnActuaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActuaProductoActionPerformed
        BtnAgregar.setVisible(false);
        BtnGrabar.setVisible(true);
        BtnBorrar.setVisible(false);
        BtnAnt.setVisible(false);
        BtnSig.setVisible(false);
        TxtNombre.setEnabled(true);
        TxtApellido.setEnabled(true);
        TxtTelefono.setEnabled(true);
    }//GEN-LAST:event_BtnActuaProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ArchBd;
    private javax.swing.JButton BtnActuaProducto;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnAnt;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnGrabar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnSig;
    private javax.swing.JMenuItem MnuAbrir;
    private javax.swing.JMenuItem MnuCon;
    private javax.swing.JPanel PnlAgenda;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
